// e2e2/src/vue/App.vue
<script setup lang="ts">
import { ProsemirrorAdapterProvider } from '@prosemirror-adapter/vue'
import { ref } from 'vue'
import Editor from './components/Editor.vue'

const counter = ref(0)
</script>

<template>
  <h1>Prosemirror Adapter Vue</h1>
  <button @click="counter++">rerender</button>
  <ProsemirrorAdapterProvider :key="counter">
    <Editor />
  </ProsemirrorAdapterProvider>
</template>

// e2e2/src/svelte/App.svelte
<script lang="ts">
  import { useProsemirrorAdapterProvider } from '@prosemirror-adapter/svelte'
  import Editor from './components/Editor.svelte'

  useProsemirrorAdapterProvider()

  let count = 0
  function handleClick() {
    count += 1
  }
</script>

<h1>Prosemirror Adapter Svelte</h1>
<button on:click={handleClick}>rerender</button>
{#key count}
  <Editor />
{/key}
