// e2e2/src/lit/App.ts
import { ShallowLitElement } from '@prosemirror-adapter/lit'
import { html } from 'lit'
import { customElement, state } from 'lit/decorators.js'
import { keyed } from 'lit/directives/keyed.js'

export * from './components/Editor'
export { ProsemirrorAdapterProvider } from '@prosemirror-adapter/lit'

@customElement('test-app')
export class App extends ShallowLitElement {
  @state()
  editorId = 0

  override render() {
    return html`
      <h1>Prosemirror Adapter Lit</h1>
      <button @click="${this._onClick}">rerender</button>
      ${keyed(
        this.editorId,
        html`
          <prosemirror-adapter-provider>
            <my-editor></my-editor>
          </prosemirror-adapter-provider>
        `,
      )}
    `
  }

  private _onClick = () => {
    this.editorId += 1
  }
}

declare global {
  interface HTMLElementTagNameMap {
    'test-app': App
  }
}

// e2e2/src/vue/App.vue
<script setup lang="ts">
import { ProsemirrorAdapterProvider } from '@prosemirror-adapter/vue'
import { ref } from 'vue'
import Editor from './components/Editor.vue'

const counter = ref(0)
</script>

<template>
  <h1>Prosemirror Adapter Vue</h1>
  <button @click="counter++">rerender</button>
  <ProsemirrorAdapterProvider :key="counter">
    <Editor />
  </ProsemirrorAdapterProvider>
</template>
