// packages/lit/src/markView/markViewContext.ts
import { ContextConsumer, createContext } from '@lit/context'
import type { LitElement } from 'lit'
import type { RefOrCallback } from 'lit/directives/ref.js'
import type { Mark } from 'prosemirror-model'
import type { EditorView, MarkViewConstructor } from 'prosemirror-view'

import type { LitMarkViewUserOptions } from './LitMarkViewOptions'

export interface MarkViewContext {
  // won't change
  contentRef: RefOrCallback
  view: EditorView
  mark: Mark
}

export const markViewContextKey = createContext<MarkViewContext>('[ProsemirrorAdapter]markViewContext')

export type ConsumeMarkViewContext = ContextConsumer<typeof markViewContextKey, LitElement>
export function useMarkViewContext(element: LitElement): ConsumeMarkViewContext {
  return new ContextConsumer(element, markViewContextKey, undefined, true)
}
export const markViewFactoryKey = createContext<MarkViewFactory>('[ProsemirrorAdapter]useMarkViewFactory')
export type MarkViewFactory = (options: LitMarkViewUserOptions) => MarkViewConstructor

export type ConsumeMarkViewFactory = ContextConsumer<typeof markViewFactoryKey, LitElement>
export function useMarkViewFactory(element: LitElement): ConsumeMarkViewFactory {
  return new ContextConsumer(element, markViewFactoryKey, undefined, true)
}

// packages/react/src/markView/markViewContext.ts
import type { Mark } from 'prosemirror-model'
import type { EditorView, MarkViewConstructor } from 'prosemirror-view'
import { createContext, useContext } from 'react'

import type { ReactMarkViewUserOptions } from './ReactMarkViewOptions'

export type MarkViewContentRef = (element: HTMLElement | null) => void

export interface MarkViewContext {
  // won't change
  contentRef: MarkViewContentRef
  view: EditorView
  mark: Mark
}

export const markViewContext = createContext<MarkViewContext>({
  contentRef: () => {
    // nothing to do
  },
  view: null as never,
  mark: null as never,
})

export const useMarkViewContext = () => useContext(markViewContext)

export const createMarkViewContext = createContext<(options: ReactMarkViewUserOptions) => MarkViewConstructor>(
  (_options) => {
    throw new Error('No ProsemirrorAdapterProvider detected, maybe you need to wrap the component with the Editor with ProsemirrorAdapterProvider?')
  },
)

export const useMarkViewFactory = () => useContext(createMarkViewContext)
