// packages/solid/src/Provider.tsx
import { type Component, For, type ParentProps } from 'solid-js'

import { createMarkViewContext } from './markView'
import { useSolidMarkViewCreator } from './markView/useSolidMarkViewCreator'
import { createNodeViewContext } from './nodeView'
import { useSolidNodeViewCreator } from './nodeView/useSolidNodeViewCreator'
import { createPluginViewContext } from './pluginView'
import { useSolidPluginViewCreator } from './pluginView/useSolidPluginViewCreator'
import { useSolidRenderer } from './SolidRenderer'
import { createWidgetViewContext } from './widgetView'
import { useSolidWidgetViewCreator } from './widgetView/useSolidWidgetViewCreator'

export const ProsemirrorAdapterProvider: Component<ParentProps> = (props) => {
  const { renderSolidRenderer, removeSolidRenderer, render } = useSolidRenderer()

  const createSolidNodeView = useSolidNodeViewCreator(renderSolidRenderer, removeSolidRenderer)

  const createSolidMarkView = useSolidMarkViewCreator(renderSolidRenderer, removeSolidRenderer)

  const createSolidWidgetView = useSolidWidgetViewCreator(renderSolidRenderer, removeSolidRenderer)

  const createSolidPluginView = useSolidPluginViewCreator(renderSolidRenderer, removeSolidRenderer)

  return (
    <createNodeViewContext.Provider value={createSolidNodeView}>
      <createMarkViewContext.Provider value={createSolidMarkView}>
        <createWidgetViewContext.Provider value={createSolidWidgetView}>
          <createPluginViewContext.Provider value={createSolidPluginView}>
            {props.children}
            <For each={render()}>{(node) => node}</For>
          </createPluginViewContext.Provider>
        </createWidgetViewContext.Provider>
      </createMarkViewContext.Provider>
    </createNodeViewContext.Provider>
  )
}

// packages/react/src/Provider.ts
import { Fragment, createElement, type FC, type ReactNode } from 'react'

import { createMarkViewContext } from './markView'
import { useReactMarkViewCreator } from './markView/useReactMarkViewCreator'
import { createNodeViewContext } from './nodeView'
import { useReactNodeViewCreator } from './nodeView/useReactNodeViewCreator'
import { createPluginViewContext } from './pluginView/pluginViewContext'
import { useReactPluginViewCreator } from './pluginView/useReactPluginViewCreator'
import { useReactRenderer } from './ReactRenderer'
import { createWidgetViewContext } from './widgetView'
import { useReactWidgetViewCreator } from './widgetView/useReactWidgetViewCreator'

export type CreateReactNodeView = ReturnType<typeof useReactNodeViewCreator>
export type CreateReactMarkView = ReturnType<typeof useReactMarkViewCreator>
export type CreateReactPluginView = ReturnType<typeof useReactPluginViewCreator>
export type CreateReactWidgetView = ReturnType<typeof useReactWidgetViewCreator>

export const ProsemirrorAdapterProvider: FC<{ children: ReactNode }> = ({ children }) => {
  const { renderReactRenderer, removeReactRenderer, render } = useReactRenderer()

  const createReactNodeView: CreateReactNodeView = useReactNodeViewCreator(renderReactRenderer, removeReactRenderer)

  const createReactMarkView: CreateReactMarkView = useReactMarkViewCreator(renderReactRenderer, removeReactRenderer)

  const createReactPluginView: CreateReactPluginView = useReactPluginViewCreator(
    renderReactRenderer,
    removeReactRenderer,
  )

  const createReactWidgetView: CreateReactWidgetView = useReactWidgetViewCreator(
    renderReactRenderer,
    removeReactRenderer,
  )

  return createElement(
    createNodeViewContext.Provider,
    { value: createReactNodeView },
    createElement(
      createMarkViewContext.Provider,
      { value: createReactMarkView },
      createElement(
        createPluginViewContext.Provider,
        { value: createReactPluginView },
        createElement(
          createWidgetViewContext.Provider,
          { value: createReactWidgetView },
          createElement(Fragment, { key: 1 }, children),
          createElement(Fragment, { key: 2 }, render()),
        ),
      ),
    ),
  )
}
