// examples/react/components/Hashes.tsx
import { useWidgetViewContext } from '@prosemirror-adapter/react'

export function Hashes() {
  const { spec } = useWidgetViewContext()
  const level = spec?.level as number
  const hashes = new Array(level || 0).fill('#').join('')

  return <span style={{ color: 'blue', marginRight: 6 }}>{hashes}</span>
}

// e2e2/src/solid/components/Hashes.tsx
import { useWidgetViewContext } from '@prosemirror-adapter/solid'
import { createMemo } from 'solid-js'

export function Hashes() {
  const context = useWidgetViewContext()
  const level = createMemo(() => context().spec?.level as number)
  const hashes = createMemo(() => new Array(level() || 0).fill('#').join(''))

  return <span style={{ color: 'blue', 'margin-right': '6px' }}>{hashes()}</span>
}
