// e2e2/src/svelte/components/Paragraph.svelte
<script lang="ts">
  import { useNodeViewContext } from '@prosemirror-adapter/svelte'
  let selected = false

  const contentRef = useNodeViewContext('contentRef')
  const selectedStore = useNodeViewContext('selected')
  selectedStore.subscribe((value) => {
    selected = value
  })
</script>

<div use:contentRef class:selected></div>

<style>
  .selected {
    outline: blue solid 1px;
  }
</style>

// e2e2/src/solid/components/Paragraph.tsx
import { useNodeViewContext } from '@prosemirror-adapter/solid'

export function Paragraph() {
  const context = useNodeViewContext()

  return (
    <div
      style={{ outline: context().selected ? 'blue solid 1px' : 'none' }}
      role="presentation"
      ref={context().contentRef}
    />
  )
}
