// packages/react/src/pluginView/pluginViewContext.ts
import type { PluginViewSpec } from '@prosemirror-adapter/core'
import type { EditorState } from 'prosemirror-state'
import type { EditorView } from 'prosemirror-view'
import { createContext, useContext } from 'react'

import type { ReactPluginViewUserOptions } from './ReactPluginViewOptions'

export type PluginViewContentRef = (element: HTMLElement | null) => void

export interface PluginViewContext {
  view: EditorView
  prevState?: EditorState
}

export const pluginViewContext = createContext<PluginViewContext>({
  view: null as never,
})

export const usePluginViewContext = () => useContext(pluginViewContext)

export const createPluginViewContext = createContext<(options: ReactPluginViewUserOptions) => PluginViewSpec>(
  (_options) => {
    throw new Error('out of scope')
  },
)

export const usePluginViewFactory = () => useContext(createPluginViewContext)

// packages/lit/src/pluginView/pluginViewContext.ts
import { ContextConsumer, createContext } from '@lit/context'
import type { PluginViewSpec } from '@prosemirror-adapter/core'
import type { LitElement } from 'lit'
import type { EditorState } from 'prosemirror-state'
import type { EditorView } from 'prosemirror-view'

import type { LitPluginViewUserOptions } from './LitPluginViewOptions'

export interface PluginViewContext {
  view: EditorView
  prevState: EditorState | undefined
}

export const pluginViewContextKey = createContext<PluginViewContext>('[ProsemirrorAdapter]pluginViewContext')
export type ConsumePluginViewContext = ContextConsumer<typeof pluginViewContextKey, LitElement>
export function usePluginViewContext(element: LitElement): ConsumePluginViewContext {
  return new ContextConsumer(element, pluginViewContextKey, undefined, true)
}

export type PluginViewFactory = (options: LitPluginViewUserOptions) => PluginViewSpec
export const pluginViewFactoryKey = createContext<PluginViewFactory>('[ProsemirrorAdapter]usePluginViewFactory')
export type ConsumePluginViewFactory = ContextConsumer<typeof pluginViewFactoryKey, LitElement>
export function usePluginViewFactory(element: LitElement): ConsumePluginViewFactory {
  return new ContextConsumer(element, pluginViewFactoryKey, undefined, true)
}
