// packages/solid/src/Provider.tsx
import { type Component, For, type ParentProps } from 'solid-js'

import { useSolidRenderer } from './SolidRenderer'
import { createMarkViewContext } from './markView'
import { useSolidMarkViewCreator } from './markView/useSolidMarkViewCreator'
import { createNodeViewContext } from './nodeView'
import { useSolidNodeViewCreator } from './nodeView/useSolidNodeViewCreator'
import { createPluginViewContext } from './pluginView'
import { useSolidPluginViewCreator } from './pluginView/useSolidPluginViewCreator'
import { createWidgetViewContext } from './widgetView'
import { useSolidWidgetViewCreator } from './widgetView/useSolidWidgetViewCreator'

export const ProsemirrorAdapterProvider: Component<ParentProps> = (props) => {
  const { renderSolidRenderer, removeSolidRenderer, portals }
    = useSolidRenderer()

  const createSolidNodeView = useSolidNodeViewCreator(
    renderSolidRenderer,
    removeSolidRenderer,
  )

  const createSolidMarkView = useSolidMarkViewCreator(
    renderSolidRenderer,
    removeSolidRenderer,
  )

  const createSolidWidgetView = useSolidWidgetViewCreator(
    renderSolidRenderer,
    removeSolidRenderer,
  )

  const createSolidPluginView = useSolidPluginViewCreator(
    renderSolidRenderer,
    removeSolidRenderer,
  )

  return (
    <createNodeViewContext.Provider value={createSolidNodeView}>
      <createMarkViewContext.Provider value={createSolidMarkView}>
        <createWidgetViewContext.Provider value={createSolidWidgetView}>
          <createPluginViewContext.Provider value={createSolidPluginView}>
            {props.children}
            <For each={Object.values(portals)}>{portal => portal}</For>
          </createPluginViewContext.Provider>
        </createWidgetViewContext.Provider>
      </createMarkViewContext.Provider>
    </createNodeViewContext.Provider>
  )
}

// packages/preact/src/Provider.tsx
import type { ComponentChildren } from 'preact'
import { useMemo } from 'preact/hooks'

import { usePreactRenderer } from './PreactRenderer'
import { createMarkViewContext } from './markView'
import { usePreactMarkViewCreator } from './markView/usePreactMarkViewCreator'
import { createNodeViewContext } from './nodeView'
import { usePreactNodeViewCreator } from './nodeView/usePreactNodeViewCreator'
import { createPluginViewContext } from './pluginView/pluginViewContext'
import { usePreactPluginViewCreator } from './pluginView/usePreactPluginViewCreator'
import { createWidgetViewContext } from './widgetView'
import { usePreactWidgetViewCreator } from './widgetView/usePreactWidgetViewCreator'

export type CreatePreactNodeView = ReturnType<typeof usePreactNodeViewCreator>
export type CreatePreactMarkView = ReturnType<typeof usePreactMarkViewCreator>
export type CreatePreactPluginView = ReturnType<typeof usePreactPluginViewCreator>
export type CreatePreactWidgetView = ReturnType<typeof usePreactWidgetViewCreator>

export function ProsemirrorAdapterProvider({ children }: { children: ComponentChildren }) {
  const { renderPreactRenderer, removePreactRenderer, portals } = usePreactRenderer()

  const createPreactNodeView: CreatePreactNodeView = usePreactNodeViewCreator(
    renderPreactRenderer,
    removePreactRenderer,
  )

  const createPreactMarkView: CreatePreactMarkView = usePreactMarkViewCreator(
    renderPreactRenderer,
    removePreactRenderer,
  )

  const createPreactPluginView: CreatePreactPluginView = usePreactPluginViewCreator(
    renderPreactRenderer,
    removePreactRenderer,
  )

  const createPreactWidgetView: CreatePreactWidgetView = usePreactWidgetViewCreator(
    renderPreactRenderer,
    removePreactRenderer,
  )

  const memoizedPortals = useMemo(() => Object.values(portals), [portals])

  return (
    <createNodeViewContext.Provider value={createPreactNodeView}>
      <createMarkViewContext.Provider value={createPreactMarkView}>
        <createPluginViewContext.Provider value={createPreactPluginView}>
          <createWidgetViewContext.Provider value={createPreactWidgetView}>
            {children}
            {memoizedPortals}
          </createWidgetViewContext.Provider>
        </createPluginViewContext.Provider>
      </createMarkViewContext.Provider>
    </createNodeViewContext.Provider>
  )
}
